README.md: guessinggame.sh
	echo "# Guessing Game Project" > README.md
	echo "Make was run on: $$(date)" >> README.md
	echo "Number of lines of code in guessinggame.sh: $$(wc -l < guessinggame.sh)" >> README.md

clean:
	rm README.md
